/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_jorphan_timer_HRTimer */

#ifndef _Included_org_apache_jorphan_timer_HRTimer
#define _Included_org_apache_jorphan_timer_HRTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_jorphan_timer_HRTimer
 * Method:    getTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_jorphan_timer_HRTimer_getTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
