# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Apache JMeter open-source load testing tool for analyzing and measuring the performance of a variety of services"
  homepage: https://jmeter.apache.org/
  labels:
    - performance
    - test
    - java

  dependabot_alerts: true
  dependabot_updates: false

  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true

  features:
    wiki: false
    issues: true
    projects: false

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@jmeter.apache.org
  issues: dev@jmeter.apache.org
  pullrequests: dev@jmeter.apache.org
  jira_options: link label
