blank_issues_enabled: true
contact_links:
  - name: JMeter users mailing list
    url: https://jmeter.apache.org/mail2.html
    about: Please ask questions on JMeter usage on users mailing list (note that you need to subscribe first)
