//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.03 at 07:33:19 GMT-05:00 
//


package org.apache.jorphan.tomcat.manager;


/**
 * Java content class for connector complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="connector">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="threadInfo" type="{}threadInfo"/>
 *         &lt;element name="requestInfo" type="{}requestInfo" minOccurs="0"/>
 *         &lt;element name="workers" type="{}workers" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="http-8080"/>
 *             &lt;enumeration value="jk8009"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Connector {


    org.apache.jorphan.tomcat.manager.ThreadInfo getThreadInfo();

    void setThreadInfo(org.apache.jorphan.tomcat.manager.ThreadInfo value);

    org.apache.jorphan.tomcat.manager.RequestInfo getRequestInfo();

    void setRequestInfo(org.apache.jorphan.tomcat.manager.RequestInfo value);

    org.apache.jorphan.tomcat.manager.Workers getWorkers();

    void setWorkers(org.apache.jorphan.tomcat.manager.Workers value);

    java.lang.String getName();

    void setName(java.lang.String value);

}
