//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.03 at 07:33:19 GMT-05:00 
//


package org.apache.jorphan.tomcat.manager;


/**
 * Java content class for memory complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="memory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="free" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="total" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="max" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Memory {


    long getMax();

    void setMax(long value);

    long getFree();

    void setFree(long value);

    long getTotal();

    void setTotal(long value);

}
