//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.03 at 07:33:19 GMT-05:00 
//


package org.apache.jorphan.tomcat.manager;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the org.apache.jorphan.tomcat.manager package. <p>An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for each of these are provided in this class.
 * 
 */
public class ObjectFactory
    extends com.sun.xml.bind.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();

    static {
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.Connector.class), (org.apache.jorphan.tomcat.manager.impl.ConnectorImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.Worker.class), (org.apache.jorphan.tomcat.manager.impl.WorkerImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.RequestInfo.class), (org.apache.jorphan.tomcat.manager.impl.RequestInfoImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.Memory.class), (org.apache.jorphan.tomcat.manager.impl.MemoryImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.Jvm.class), (org.apache.jorphan.tomcat.manager.impl.JvmImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.Workers.class), (org.apache.jorphan.tomcat.manager.impl.WorkersImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.ThreadInfo.class), (org.apache.jorphan.tomcat.manager.impl.ThreadInfoImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.StatusType.class), (org.apache.jorphan.tomcat.manager.impl.StatusTypeImpl.class));
        defaultImplementations.put((org.apache.jorphan.tomcat.manager.Status.class), (org.apache.jorphan.tomcat.manager.impl.StatusImpl.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.jorphan.tomcat.manager
     * 
     */
    public ObjectFactory() {
        super(new org.apache.jorphan.tomcat.manager.ObjectFactory.GrammarInfoImpl());
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface the Class object of the javacontent interface to instantiate
     * @return a new instance
     * @throws JAXBException if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name the name of the property to retrieve
     * @return the value of the requested property
     * @throws PropertyException when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name the name of the property to retrieve
     * @param value the value of the property to be set
     * @throws PropertyException when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Connector
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.Connector createConnector()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.Connector) newInstance((org.apache.jorphan.tomcat.manager.Connector.class)));
    }

    /**
     * Create an instance of Worker
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.Worker createWorker()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.Worker) newInstance((org.apache.jorphan.tomcat.manager.Worker.class)));
    }

    /**
     * Create an instance of RequestInfo
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.RequestInfo createRequestInfo()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.RequestInfo) newInstance((org.apache.jorphan.tomcat.manager.RequestInfo.class)));
    }

    /**
     * Create an instance of Memory
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.Memory createMemory()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.Memory) newInstance((org.apache.jorphan.tomcat.manager.Memory.class)));
    }

    /**
     * Create an instance of Jvm
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.Jvm createJvm()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.Jvm) newInstance((org.apache.jorphan.tomcat.manager.Jvm.class)));
    }

    /**
     * Create an instance of Workers
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.Workers createWorkers()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.Workers) newInstance((org.apache.jorphan.tomcat.manager.Workers.class)));
    }

    /**
     * Create an instance of ThreadInfo
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.ThreadInfo createThreadInfo()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.ThreadInfo) newInstance((org.apache.jorphan.tomcat.manager.ThreadInfo.class)));
    }

    /**
     * Create an instance of StatusType
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.StatusType createStatusType()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.StatusType) newInstance((org.apache.jorphan.tomcat.manager.StatusType.class)));
    }

    /**
     * Create an instance of Status
     * 
     * @throws JAXBException if an error occurs
     */
    public org.apache.jorphan.tomcat.manager.Status createStatus()
        throws javax.xml.bind.JAXBException
    {
        return ((org.apache.jorphan.tomcat.manager.Status) newInstance((org.apache.jorphan.tomcat.manager.Status.class)));
    }

    private static class GrammarInfoImpl
        extends com.sun.xml.bind.GrammarInfo
    {


        public java.lang.Class getDefaultImplementation(java.lang.Class javaContentInterface) {
            return ((java.lang.Class) defaultImplementations.get(javaContentInterface));
        }

        public java.lang.Class getRootElement(java.lang.String uri, java.lang.String local) {
            if (("" == uri)&&("status" == local)) {
                return (org.apache.jorphan.tomcat.manager.impl.StatusImpl.class);
            }
            return null;
        }

        public java.lang.String[] getProbePoints() {
            return new java.lang.String[] {"", "status"};
        }

    }

}
