//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.03 at 07:33:19 GMT-05:00 
//


package org.apache.jorphan.tomcat.manager;


/**
 * Java content class for requestInfo complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="requestInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="errorCount" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="processingTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="requestCount" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="bytesSent" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="maxTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bytesReceived" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RequestInfo {


    long getBytesReceived();

    void setBytesReceived(long value);

    long getBytesSent();

    void setBytesSent(long value);

    long getRequestCount();

    void setRequestCount(long value);

    long getErrorCount();

    void setErrorCount(long value);

    int getMaxTime();

    void setMaxTime(int value);

    int getProcessingTime();

    void setProcessingTime(int value);

}
