//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.03 at 07:33:19 GMT-05:00 
//


package org.apache.jorphan.tomcat.manager;


/**
 * Java content class for threadInfo complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="threadInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="minSpareThreads" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="currentThreadCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maxThreads" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="currentThreadsBusy" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maxSpareThreads" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ThreadInfo {


    int getMaxSpareThreads();

    void setMaxSpareThreads(int value);

    int getMinSpareThreads();

    void setMinSpareThreads(int value);

    int getMaxThreads();

    void setMaxThreads(int value);

    int getCurrentThreadsBusy();

    void setCurrentThreadsBusy(int value);

    int getCurrentThreadCount();

    void setCurrentThreadCount(int value);

}
