//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.03 at 07:33:19 GMT-05:00 
//


package org.apache.jorphan.tomcat.manager;


/**
 * Java content class for worker complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="worker">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="requestBytesSent" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="stage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="requestBytesReceived" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="requestProcessingTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="currentQueryString" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="virtualHost" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="protocol" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currentUri" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="method" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="remoteAddr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Worker {


    int getRequestProcessingTime();

    void setRequestProcessingTime(int value);

    long getRequestBytesSent();

    void setRequestBytesSent(long value);

    java.lang.String getCurrentQueryString();

    void setCurrentQueryString(java.lang.String value);

    java.lang.String getRemoteAddr();

    void setRemoteAddr(java.lang.String value);

    java.lang.String getCurrentUri();

    void setCurrentUri(java.lang.String value);

    java.lang.String getStage();

    void setStage(java.lang.String value);

    java.lang.String getVirtualHost();

    void setVirtualHost(java.lang.String value);

    java.lang.String getProtocol();

    void setProtocol(java.lang.String value);

    long getRequestBytesReceived();

    void setRequestBytesReceived(long value);

    java.lang.String getMethod();

    void setMethod(java.lang.String value);

}
