Ehmmm, the problem is that I'm not a UNIX person and I don't know how to
write a makefile :-( even a simple one like required here.

So, if you are so kind to donate a couple of minutes of your free time to port
the make.bat script to the makefile world, drop me a note and I'll be very happy

Stefano Mazzocchi <stefano@apache.org>