name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    if: github.repository == 'apache/jmeter'
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
