name: Validate Renovate Config

on:
  push:
    paths:
      - renovate.json
      - .github/workflows/renovate-config-lint.yaml
  pull_request:
    paths:
      - renovate.json
      - .github/workflows/renovate-config-lint.yaml

# Declare default permissions as read-only.
permissions: read-all

jobs:
  validate-renovate-config:
    name: Validate renovate.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false

      - name: Validate renovate.json
        run: docker run --rm -v "$PWD":/work -w /work renovate/renovate:latest renovate-config-validator renovate.json
